C_OBJS=exe_self_suspended.o
ASM_OBJS=
COMPONENT=exe_ss.o
INTERFACES=exe_self_suspension
DEPENDENCIES=cbufp cbuf_c sched printc mem_mgr_large valloc lock timed_blk ll_log
IF_LIB=

include ../../Makefile.subsubdir

