C_OBJS=cbuf_mid.o
ASM_OBJS=
COMPONENT=cbf_mid.o
INTERFACES=cbuf_mid
DEPENDENCIES=cbufp cbuf_c cbuf_bot mem_mgr_large valloc printc lock sched ll_log monitor_upcall
IF_LIB=

include ../../Makefile.subsubdir

