C_OBJS=booter.o
ASM_OBJS=
COMPONENT=boot.o
INTERFACES=cinfo failure_notif cgraph
DEPENDENCIES=sched printc mem_mgr recovery_upcall
IF_LIB=
ADDITIONAL_LIBS=-lcobj_format

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
