C_OBJS=lock.o
ASM_OBJS=
COMPONENT=l.o
INTERFACES=lock
DEPENDENCIES=sched mem_mgr printc timed_blk ll_log monitor_upcall valloc_local
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
