C_OBJS=ramfs_ft_test1.o
ASM_OBJS=
COMPONENT=ramfs_rec_test1.o
INTERFACES=
DEPENDENCIES=periodic_wake sched printc cbufp cbuf_c rtorrent evt mem_mgr_large valloc lock ramfs_test2 timed_blk pgfault ll_log
IF_LIB=

include ../../Makefile.subsubdir
