C_OBJS=synth_hier.o
COMPONENT=sh.o
INTERFACES=synth_hier
DEPENDENCIES=sched printc synth_hier lock mem_mgr_large valloc ll_log monitor_upcall
FN_PREPEND=calll_ callr_

include ../../Makefile.subsubdir

