C_OBJS=mem_pool.o
ASM_OBJS=
COMPONENT=mpool.o
INTERFACES=mem_pool
DEPENDENCIES=mem_mgr_large printc sched cinfo lock ll_log valloc
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
