C_OBJS=clm.o
ASM_OBJS=
COMPONENT=lmon.o
INTERFACES=logmonitor
DEPENDENCIES=sched mem_mgr_large lock valloc printc periodic_wake timed_blk

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
