C_OBJS=timed_event.o
ASM_OBJS=
COMPONENT=te.o
INTERFACES=timed_blk periodic_wake
DEPENDENCIES=printc lock sched mem_mgr pgfault ll_log  
IF_LIB=

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
