C_OBJS=pop_server_file.o
ASM_OBJS=
COMPONENT=popcgi.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock timed_blk ll_log
IF_LIB=

include ../../Makefile.subsubdir
