C_OBJS=conn_mgr.o
ASM_OBJS=
COMPONENT=stconnmt.o
INTERFACES=lateness_report
DEPENDENCIES=torrent printc mem_mgr_large sched valloc cbufp cbuf_c evt periodic_wake net_transport lock ll_log
IF_LIB=
FN_PREPEND=from_

include ../../Makefile.subsubdir
