C_OBJS=content_mgr.o
COMPONENT=cm.o
INTERFACES=content_mux
DEPENDENCIES=printc mem_mgr_large static_content lock sched async_inv valloc ll_log monitor_upcall
FN_PREPEND=alt_

include ../../Makefile.subsubdir

