C_OBJS=mpd_mgr.o
ASM_OBJS=
COMPONENT=mpd.o
INTERFACES=
DEPENDENCIES=lock sched printc timed_blk mem_mgr_large cgraph valloc ll_log monitor_upcall
IF_LIB=
ADDITIONAL_LIBS=-lheap

include ../../Makefile.subsubdir

