C_OBJS=cbufp.o
ASM_OBJS=
COMPONENT=bufp.o
INTERFACES=cbufp
DEPENDENCIES=cbuf_c sched printc lock mem_mgr_large valloc ll_log monitor_upcall

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
