C_OBJS=cos_ip.o
ASM_OBJS=
COMPONENT=tip.o
INTERFACES=torrent
DEPENDENCIES=cbufp cbuf_c torrent printc lock sched valloc periodic_wake uniq_map evt mem_mgr_large ll_log
FN_PREPEND=parent_

include ../../Makefile.subsubdir
