C_OBJS=torrent_test.o
ASM_OBJS=
COMPONENT=tt.o
INTERFACES=
DEPENDENCIES=printc torrent sched cbufp cbuf_c evt mem_mgr_large valloc lock ll_log monitor_upcall
IF_LIB=

include ../../Makefile.subsubdir

