C_OBJS=uniq_map.o
ASM_OBJS=
COMPONENT=unique_map.o
INTERFACES=uniq_map
DEPENDENCIES=sched printc cbufp cbuf_c lock mem_mgr_large valloc ll_log

include ../../Makefile.subsubdir
MANDITORY_LIB=simple_stklib.o
