C_OBJS=ramfs_ft_test2.o
ASM_OBJS=
COMPONENT=ramfs_rec_test2.o
INTERFACES=ramfs_test2
DEPENDENCIES=printc rtorrent sched cbufp cbuf_c evt mem_mgr_large valloc lock ll_log
IF_LIB=

include ../../Makefile.subsubdir
