C_OBJS=ramfs.o
ASM_OBJS=
COMPONENT=rfs.o
INTERFACES=rtorrent
DEPENDENCIES=printc cbuf_c evt lock mem_mgr_large valloc uniq_map pgfault
#DEPENDENCIES=printc cbuf_c evt lock mem_mgr_large valloc uniq_map

include ../../Makefile.subsubdir

